version: "3.8"  # optional since v1.27.0
services:
  
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    # env_file Will be overriden by the environmen variables in elasticbeanstalk configuration.
    env_file:
      - .env
  dauth:
    image: jameswrc/dauthbackend:arm64v8
    # env_file Will be overriden by the environmen variables in elasticbeanstalk configuration.
    env_file:
      - .env 
    labels:
      - traefik.enable=true
      - "traefik.http.routers.dauth.rule=Host(`${SUBDOMAIN}.${ZONE}`)"
      - traefik.http.routers.dauth.tls=true
      - traefik.http.routers.dauth.tls.certresolver=myresolver
      - traefik.http.routers.dauth.entrypoints=websecure
      - traefik.http.routers.dauth.entrypoints
      - traefik.wss.protocol=https

  traefik:
    image: traefik:v2.5
    ports:
      - 8080:8080
      - 80:80
      - 443:443
    expose:
      - 8080
      - 80
      - 443
    env_file:
      - .env
    # Any command for Traefik should be appended in the entrypoint below in the 'entrypoint'.
    command:
      - "--api=true"
      - "--api.insecure=true"
    entrypoint: sh -c "sleep 30 && ./entrypoint.sh --api=true --api.insecure=true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.entrypoints=web"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.dauth.dev`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=auth"    
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./services/traefik/:/etc/traefik/"
  
  cf_acme_kv_cache:
    image: jameswrc/cfacmekvcache:arm64v8
    env_file:
      - .env
    volumes:
      - "./services/traefik/:/etc/traefik/"
