version: "3.9"  # optional since v1.27.0
services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    restart: always
    env_file:
      - .env
  dauth:
    build:
       context: .
    expose:
      - 3000
    ports:
      - 3000:3000
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.http.routers.dauth.rule=Host(`soc1.dauth.dev`)
      - traefik.http.routers.dauth.tls=true
      - traefik.http.routers.dauth.tls.certresolver=myresolver
      - traefik.http.routers.dauth.entrypoints=websecure
      - traefik.http.services.dauth.loadbalancer.server.port=3000
      - "traefik.frontend.headers.SSLProxyHeaders=X-Forwarded-Proto: https"
      - "traefik.frontend.headers.SSLRedirect=true"
      
  traefik:
    build: 
      context: .
      dockerfile: traefik.docker
    ports:
      - 8080:8080
      - 80:80
      - 443:443
    expose:
      - 8080
      - 80
      - 443
    env_file:
      - .env
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./services/traefik/:/etc/traefik/"
