version: "3.9"  # optional since v1.27.0
services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    # env_file Will be overriden by the environmen variables in elasticbeanstalk configuration.
    env_file:
      - .env
  dauth:
    build:
       context: .
    # env_file Will be overriden by the environmen variables in elasticbeanstalk configuration.
    env_file:
      - .env 
    labels:
      - traefik.enable=true
      - "traefik.http.routers.dauth.rule=Host(`${SUBDOMAIN}.${ZONE}`)"
      - traefik.http.routers.dauth.tls=true
      - traefik.http.routers.dauth.tls.certresolver=myresolver
      - traefik.http.routers.dauth.entrypoints=websecure

  traefik:
    image: traefik:v2.5
    ports:
      - 8080:8080
      - 80:80
      - 443:443
    expose:
      - 8080
      - 80
      - 443
    env_file:
      - .env
    command:
      - "--api=true"
      - "--api.insecure=true"
    labels:
      - "traefik.http.routers.dashboard.rule=Host(`traefik.dauth.dev`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=test:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/,test2:$$apr1$$d9hr9HBB$$4HxwgUir3HP4EsggP/QNo0"
    
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./services/traefik/:/etc/traefik/"
    depends_on:
      - cf_acme_kv_cache
  
  cf_acme_kv_cache:
    image: jameswrc/cfacmekvcache:arm64v8
    env_file:
      - .env
    volumes:
      - "./services/traefik/:/etc/traefik/"
    healthcheck:
      test: ["CMD", "sh", "isReadyAndHealthy.sh"]
      interval: 20s
      timeout: 1s
      retries: 30
      start_period: 10s
