log:
  level: DEBUG

entryPoints:
  websecure:
    address: ':3000'

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: true

http:
  routers:
    Router-1:
      rule: "Host(`sco1.dauth.dev`) "
      service: dauth
      # will terminate the TLS request
      tls: {}

certificatesResolvers:
  myresolver:
    acme:
      email: james.cockshott@pm.me
      storage: acme.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"